# .github/FUNDING.yml

# GitHub Sponsors (replace with one or more usernames)
#github: [Nodrex]

# Patreon
patreon: Nodrex #["https://www.patreon.com/c/Nodrex"]


# Custom URL (e.g., Buy Me a Coffee, PayPal. Must be a list)
#custom: ["https://www.buymeacoffee.com/YourUsername"]