name: Lint and Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lintDebug
        run: ./gradlew lintDebug
      
      # This step is currently disabled. Uncomment it when you add unit tests.
      # - name: Run Unit Tests
      #   run: ./gradlew test

      - name: Build project for release
        run: ./gradlew assembleRelease
